"""initial schema with correct table names

Revision ID: a328ee925b2b
Revises: 
Create Date: 2026-05-14 07:43:58.168032+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a328ee925b2b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email (unique, case-insensitive)'),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='Bcrypt hashed password (NULL for OAuth-only users)'),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.Enum('USER', 'PREMIUM', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='Account locked until this timestamp (brute force protection)'),
    sa.Column('failed_login_count', sa.Integer(), nullable=False, comment='Consecutive failed login attempts'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True, comment='IPv4 or IPv6 of last login'),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (NULL = active)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('LOGIN', 'LOGIN_FAILED', 'LOGOUT', 'PASSWORD_CHANGED', 'EMAIL_CHANGED', 'TWO_FACTOR_ENABLED', 'TWO_FACTOR_DISABLED', 'ACCOUNT_CREATED', 'ACCOUNT_DELETED', 'ACCOUNT_LOCKED', 'ACCOUNT_UNLOCKED', 'DATA_EXPORTED', 'PROFILE_UPDATED', 'CARD_ADDED', 'CARD_REMOVED', 'BANK_LINKED', 'BANK_UNLINKED', 'CHAT_STARTED', 'RECOMMENDATION_GENERATED', name='audit_action'), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True, comment="Hangi kaynak (örn: 'credit_card', 'conversation')"),
    sa.Column('resource_id', sa.String(length=255), nullable=True, comment='Kaynak ID'),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Olaya özel ek bilgi (eski değer/yeni değer, vb.)'),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_action_occurred', 'audit_logs', ['action', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_user_occurred', 'audit_logs', ['user_id', 'occurred_at'], unique=False)
    op.create_table('budgets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('GROCERY', 'DINING', 'TRANSPORT', 'UTILITIES', 'RENT', 'HEALTHCARE', 'ENTERTAINMENT', 'CLOTHING', 'ELECTRONICS', 'EDUCATION', 'TRAVEL', 'SUBSCRIPTION', 'HOME', 'PERSONAL_CARE', 'GIFTS', 'OTHER', name='expense_category'), nullable=False),
    sa.Column('monthly_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_spent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('alert_at_percentage', sa.Integer(), nullable=False, comment='Yüzde kaçta uyarı versin? (50, 75, 80, 90, 100)'),
    sa.Column('last_alert_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.CheckConstraint('alert_at_percentage >= 0 AND alert_at_percentage <= 100', name=op.f('ck_budgets_alert_at_percentage_range')),
    sa.CheckConstraint('monthly_limit > 0', name=op.f('ck_budgets_monthly_limit_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_budgets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budgets'))
    )
    op.create_index(op.f('ix_budgets_user_id'), 'budgets', ['user_id'], unique=False)
    op.create_index('uq_budgets_user_category', 'budgets', ['user_id', 'category'], unique=True)
    op.create_table('comparisons',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('products', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="Karşılaştırılan ürünlerin tam snapshot'ı"),
    sa.Column('ai_recommendation', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="AI'ın bu karşılaştırma için verdiği tavsiye"),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comparisons_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comparisons'))
    )
    op.create_index(op.f('ix_comparisons_user_id'), 'comparisons', ['user_id'], unique=False)
    op.create_table('coupons',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False, comment='Pazaryeri (trendyol, hepsiburada, vs.)'),
    sa.Column('code', sa.String(length=100), nullable=True, comment='Kupon kodu (varsa)'),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('coupon_type', sa.Enum('AMOUNT', 'PERCENTAGE', name='coupon_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='Sabit tutar (TYPE=amount ise)'),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True, comment='Yüzde (TYPE=percentage ise, 0-100)'),
    sa.Column('min_basket_amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='Min. sepet tutarı'),
    sa.Column('max_discount_amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='Maks. indirim (% kuponlarda)'),
    sa.Column('applicable_categories', postgresql.ARRAY(sa.String()), nullable=True, comment='Geçerli kategoriler (boş = tüm kategoriler)'),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.CheckConstraint('percentage IS NULL OR (percentage >= 0 AND percentage <= 100)', name=op.f('ck_coupons_percentage_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_coupons_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupons'))
    )
    op.create_index(op.f('ix_coupons_expires_at'), 'coupons', ['expires_at'], unique=False)
    op.create_index('ix_coupons_user_expires', 'coupons', ['user_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_coupons_user_id'), 'coupons', ['user_id'], unique=False)
    op.create_table('credit_cards',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False, comment="Kullanıcının verdiği isim (örn: 'İş Kartı', 'Alışveriş Kartı')"),
    sa.Column('bank', sa.Enum('AKBANK', 'GARANTI', 'ISBANK', 'YAPIKREDI', 'ZIRAAT', 'HALKBANK', 'VAKIFBANK', 'QNB', 'OTHER', name='bank_code'), nullable=False),
    sa.Column('card_type', sa.Enum('AXESS', 'BONUS', 'WORLD', 'MAXIMUM', 'BANKKART', 'PARAF', 'CARDFINANS', 'OTHER', name='card_type'), nullable=False),
    sa.Column('last_four_digits', sa.String(length=4), nullable=True, comment='Sadece son 4 hane (görüntüleme için)'),
    sa.Column('total_limit', sa.Numeric(precision=12, scale=2), nullable=False, comment='Toplam kart limiti'),
    sa.Column('available_limit', sa.Numeric(precision=12, scale=2), nullable=False, comment='Anlık kullanılabilir limit'),
    sa.Column('statement_day', sa.Integer(), nullable=True, comment='Hesap kesim günü (1-28)'),
    sa.Column('payment_due_day', sa.Integer(), nullable=True, comment='Son ödeme günü'),
    sa.Column('points_per_lira', sa.Numeric(precision=5, scale=4), nullable=False, comment='1 TL harcamada kazanılan puan'),
    sa.Column('current_points', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('installment_options', postgresql.ARRAY(sa.Integer()), nullable=False, comment='Bu kart için mevcut taksit seçenekleri'),
    sa.Column('default_interest_rate', sa.Numeric(precision=6, scale=4), nullable=False, comment='Yıllık nominal faiz oranı (banka varsayılanı)'),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='Varsayılan kart mı?'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (NULL = active)'),
    sa.CheckConstraint('available_limit <= total_limit', name=op.f('ck_credit_cards_available_limit_lte_total')),
    sa.CheckConstraint('payment_due_day IS NULL OR (payment_due_day >= 1 AND payment_due_day <= 28)', name=op.f('ck_credit_cards_payment_due_day_range')),
    sa.CheckConstraint('statement_day IS NULL OR (statement_day >= 1 AND statement_day <= 28)', name=op.f('ck_credit_cards_statement_day_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_credit_cards_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_cards'))
    )
    op.create_index(op.f('ix_credit_cards_deleted_at'), 'credit_cards', ['deleted_at'], unique=False)
    op.create_index('ix_credit_cards_user_active', 'credit_cards', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_credit_cards_user_id'), 'credit_cards', ['user_id'], unique=False)
    op.create_table('favorite_folders',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorite_folders_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favorite_folders'))
    )
    op.create_index(op.f('ix_favorite_folders_user_id'), 'favorite_folders', ['user_id'], unique=False)
    op.create_table('financial_goals',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='Emoji veya icon kodu'),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_contribution', sa.Numeric(precision=10, scale=2), nullable=True, comment='Aylık planlanan katkı'),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ACHIEVED', 'PAUSED', 'CANCELLED', name='goal_status'), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.CheckConstraint('current_amount >= 0', name=op.f('ck_financial_goals_current_amount_non_negative')),
    sa.CheckConstraint('target_amount > 0', name=op.f('ck_financial_goals_target_amount_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_financial_goals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_goals'))
    )
    op.create_index(op.f('ix_financial_goals_user_id'), 'financial_goals', ['user_id'], unique=False)
    op.create_table('financial_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('monthly_income', sa.Numeric(precision=12, scale=2), nullable=True, comment='Aylık net gelir (TL)'),
    sa.Column('monthly_fixed_expenses', sa.Numeric(precision=12, scale=2), nullable=True, comment='Aylık sabit giderler (kira, faturalar, kredi)'),
    sa.Column('monthly_variable_budget', sa.Numeric(precision=12, scale=2), nullable=True, comment='Aylık değişken bütçe (alışveriş, eğlence)'),
    sa.Column('monthly_savings_target', sa.Numeric(precision=12, scale=2), nullable=True, comment='Aylık tasarruf hedefi'),
    sa.Column('yearly_savings_target', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('current_total_savings', sa.Numeric(precision=12, scale=2), nullable=False, comment="Toplam birikim (manuel girilir veya banka API'sinden çekilir)"),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='ISO 4217 currency code'),
    sa.Column('risk_tolerance', sa.Integer(), nullable=False, comment='1=çok muhafazakar, 10=çok agresif'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.CheckConstraint('monthly_fixed_expenses IS NULL OR monthly_fixed_expenses >= 0', name=op.f('ck_financial_profiles_monthly_fixed_expenses_non_negative')),
    sa.CheckConstraint('monthly_income IS NULL OR monthly_income >= 0', name=op.f('ck_financial_profiles_monthly_income_non_negative')),
    sa.CheckConstraint('risk_tolerance >= 1 AND risk_tolerance <= 10', name=op.f('ck_financial_profiles_risk_tolerance_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_financial_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_financial_profiles_user_id'))
    )
    op.create_table('folders',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True, comment='Hex color veya tailwind class'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='Emoji veya icon kodu'),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_folders_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_folders'))
    )
    op.create_index(op.f('ix_folders_user_id'), 'folders', ['user_id'], unique=False)
    op.create_table('notification_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_frequency', sa.Enum('INSTANT', 'DAILY', 'WEEKLY', 'DISABLED', name='notification_frequency'), nullable=False),
    sa.Column('type_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Her notification_type için kanal tercihi'),
    sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=True, comment="HH:MM format (örn: '22:00')"),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=True, comment="HH:MM format (örn: '08:00')"),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_settings')),
    sa.UniqueConstraint('user_id', name=op.f('uq_notification_settings_user_id'))
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('PRICE_DROP', 'BACK_IN_STOCK', 'PRICE_ALERT_TRIGGERED', 'BUDGET_THRESHOLD', 'BUDGET_EXCEEDED', 'GOAL_PROGRESS', 'GOAL_ACHIEVED', 'COUPON_EXPIRING', 'NEW_COUPON', 'RECURRING_PAYMENT_DUE', 'AI_INSIGHT', 'SECURITY_ALERT', 'SYSTEM_ANNOUNCEMENT', 'ACCOUNT_ACTIVITY', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True, comment='Tıklandığında gidilecek URL'),
    sa.Column('action_label', sa.String(length=100), nullable=True, comment='Action button text'),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Bildirim tipine özel ek veri'),
    sa.Column('channels', postgresql.ARRAY(sa.String()), nullable=False, comment='Gönderildiği kanallar'),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'READ', 'FAILED', name='notification_status'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True, comment='İleri tarihli bildirimler için'),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('oauth_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE', 'APPLE', name='oauth_provider'), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False, comment="OAuth provider'ın kendi user ID'si"),
    sa.Column('provider_email', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('raw_user_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_accounts'))
    )
    op.create_index(op.f('ix_oauth_accounts_user_id'), 'oauth_accounts', ['user_id'], unique=False)
    op.create_index('uq_oauth_provider_account', 'oauth_accounts', ['provider', 'provider_account_id'], unique=True)
    op.create_table('preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('favorite_brands', postgresql.ARRAY(sa.String()), nullable=False, comment='Sevilen markalar (whitelist)'),
    sa.Column('blocked_brands', postgresql.ARRAY(sa.String()), nullable=False, comment='Tercih edilmeyen markalar (blacklist)'),
    sa.Column('preferred_marketplaces', postgresql.ARRAY(sa.String()), nullable=False, comment='Tercih edilen pazaryerleri (trendyol, hepsiburada, vs.)'),
    sa.Column('payment_preference', sa.Enum('CASH', 'INSTALLMENT', 'CREDIT', 'MIXED', name='payment_preference'), nullable=False),
    sa.Column('price_quality_balance', sa.Integer(), nullable=False, comment='1=en ucuz öncelik, 10=en kalite öncelik'),
    sa.Column('interested_categories', postgresql.ARRAY(sa.String()), nullable=False, comment='İlgilenilen ürün kategorileri'),
    sa.Column('custom_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Genişletilebilir custom ayarlar'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.CheckConstraint('price_quality_balance >= 1 AND price_quality_balance <= 10', name=op.f('ck_preferences_price_quality_balance_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preferences')),
    sa.UniqueConstraint('user_id', name=op.f('uq_preferences_user_id'))
    )
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='gender'), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True, comment='İl (örn: İstanbul, Ankara)'),
    sa.Column('district', sa.String(length=100), nullable=True, comment='İlçe/semt'),
    sa.Column('country', sa.String(length=2), nullable=False, comment='ISO 3166-1 alpha-2 country code'),
    sa.Column('occupation', sa.Enum('SALARIED', 'FREELANCER', 'BUSINESS_OWNER', 'STUDENT', 'RETIRED', 'PUBLIC_SERVANT', 'UNEMPLOYED', 'OTHER', name='occupation'), nullable=True, comment='Meslek (finans tavsiyelerini etkiler)'),
    sa.Column('occupation_detail', sa.String(length=255), nullable=True, comment='Mesleğin serbest metin açıklaması'),
    sa.Column('marital_status', sa.Enum('SINGLE', 'MARRIED_NO_KIDS', 'MARRIED_WITH_KIDS', 'SINGLE_PARENT', 'PREFER_NOT_TO_SAY', name='marital_status'), nullable=True),
    sa.Column('number_of_children', sa.Integer(), nullable=True, comment='Çocuk sayısı (aile alışverişleri için)'),
    sa.Column('bio', sa.Text(), nullable=True, comment='Kullanıcının kendi tanımı (max 500 karakter)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.CheckConstraint('number_of_children >= 0 AND number_of_children <= 20', name=op.f('ck_profiles_number_of_children_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_profiles_user_id'))
    )
    op.create_table('push_subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False, comment="Browser's push service URL"),
    sa.Column('p256dh_key', sa.Text(), nullable=False, comment='Public key (encryption)'),
    sa.Column('auth_key', sa.Text(), nullable=False, comment='Auth secret'),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True, comment='desktop, mobile, tablet'),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_push_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_subscriptions')),
    sa.UniqueConstraint('endpoint', name=op.f('uq_push_subscriptions_endpoint'))
    )
    op.create_index('ix_push_subscriptions_user_active', 'push_subscriptions', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('recurring_payments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('category', sa.Enum('GROCERY', 'DINING', 'TRANSPORT', 'UTILITIES', 'RENT', 'HEALTHCARE', 'ENTERTAINMENT', 'CLOTHING', 'ELECTRONICS', 'EDUCATION', 'TRAVEL', 'SUBSCRIPTION', 'HOME', 'PERSONAL_CARE', 'GIFTS', 'OTHER', name='expense_category'), nullable=False),
    sa.Column('frequency', sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', 'WEEKLY', name='recurring_frequency'), nullable=False),
    sa.Column('payment_day', sa.Integer(), nullable=False, comment='Ayın hangi günü (1-31)'),
    sa.Column('is_auto_paid', sa.Boolean(), nullable=False, comment='Bankada otomatik ödemeye bağlanmış mı?'),
    sa.Column('notify_enabled', sa.Boolean(), nullable=False, comment='Bildirim gönderilsin mi?'),
    sa.Column('notify_days_before', sa.Integer(), nullable=False, comment='Kaç gün önce hatırlat?'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (NULL = active)'),
    sa.CheckConstraint('amount > 0', name=op.f('ck_recurring_payments_amount_positive')),
    sa.CheckConstraint('notify_days_before >= 0 AND notify_days_before <= 30', name=op.f('ck_recurring_payments_notify_days_before_range')),
    sa.CheckConstraint('payment_day >= 1 AND payment_day <= 31', name=op.f('ck_recurring_payments_payment_day_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recurring_payments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recurring_payments'))
    )
    op.create_index(op.f('ix_recurring_payments_deleted_at'), 'recurring_payments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_recurring_payments_user_id'), 'recurring_payments', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True, comment="User-friendly device name (e.g., 'Chrome on Windows')"),
    sa.Column('device_type', sa.String(length=50), nullable=True, comment='mobile, desktop, tablet'),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True, comment='City, Country (IP-based geolocation)'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='Session manually revoked (logout)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_refresh_token_hash'), 'sessions', ['refresh_token_hash'], unique=True)
    op.create_index('ix_sessions_user_expires', 'sessions', ['user_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('two_factor_secrets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('encrypted_secret', sa.Text(), nullable=False, comment='AES-256 encrypted TOTP secret'),
    sa.Column('backup_codes', postgresql.ARRAY(sa.String()), nullable=False, comment='Hashed backup recovery codes'),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True, comment='2FA aktivasyonu tamamlandığında set olur'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_two_factor_secrets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_two_factor_secrets')),
    sa.UniqueConstraint('user_id', name=op.f('uq_two_factor_secrets_user_id'))
    )
    op.create_table('conversations',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False, comment='AI ile otomatik oluşturulur, kullanıcı düzenleyebilir'),
    sa.Column('summary', sa.Text(), nullable=True, comment='AI ile oluşturulan kısa özet'),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False, comment='Kullanıcı etiketleri (#tv, #hediye, vs.)'),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'SHARED', name='conversation_status'), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('share_token', sa.String(length=255), nullable=True, comment='Public share URL token (NULL = paylaşılmadı)'),
    sa.Column('shared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (NULL = active)'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name=op.f('fk_conversations_folder_id_folders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_deleted_at'), 'conversations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_conversations_folder_id'), 'conversations', ['folder_id'], unique=False)
    op.create_index(op.f('ix_conversations_last_message_at'), 'conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_share_token'), 'conversations', ['share_token'], unique=True)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_index('ix_conversations_user_last_message', 'conversations', ['user_id', 'last_message_at'], unique=False)
    op.create_index('ix_conversations_user_status', 'conversations', ['user_id', 'status'], unique=False)
    op.create_table('expenses',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('category', sa.Enum('GROCERY', 'DINING', 'TRANSPORT', 'UTILITIES', 'RENT', 'HEALTHCARE', 'ENTERTAINMENT', 'CLOTHING', 'ELECTRONICS', 'EDUCATION', 'TRAVEL', 'SUBSCRIPTION', 'HOME', 'PERSONAL_CARE', 'GIFTS', 'OTHER', name='expense_category'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('merchant', sa.String(length=200), nullable=True, comment='Satıcı/işyeri adı'),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False, comment='manual, mock_bank, receipt_ocr, vs.'),
    sa.Column('credit_card_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.CheckConstraint('amount > 0', name=op.f('ck_expenses_amount_positive')),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], name=op.f('fk_expenses_credit_card_id_credit_cards'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_expenses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    op.create_index(op.f('ix_expenses_category'), 'expenses', ['category'], unique=False)
    op.create_index(op.f('ix_expenses_expense_date'), 'expenses', ['expense_date'], unique=False)
    op.create_index('ix_expenses_user_category', 'expenses', ['user_id', 'category'], unique=False)
    op.create_index('ix_expenses_user_date', 'expenses', ['user_id', 'expense_date'], unique=False)
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    op.create_table('favorites',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('product_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Ürün bilgisi (name, image, platform, url, category, vs.)'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='Son bilinen fiyat'),
    sa.Column('initial_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='Favoriye eklenirken fiyat'),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['folder_id'], ['favorite_folders.id'], name=op.f('fk_favorites_folder_id_favorite_folders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorites_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favorites'))
    )
    op.create_index('ix_favorites_user_folder', 'favorites', ['user_id', 'folder_id'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', 'TOOL', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Her ajanın adımı (Research, Needs, Market, ..., Auditor)'),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Kaynak URL'leri ve özetleri"),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Foto, ses dosyaları, vb.'),
    sa.Column('model_used', sa.String(length=100), nullable=True, comment='Hangi Gemini modeli kullanıldı'),
    sa.Column('tokens_used', sa.Integer(), nullable=True, comment='Toplam token (input + output)'),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True, comment='0.00-1.00 arası güven skoru'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='Cevap üretim süresi (ms)'),
    sa.Column('auditor_rejected_count', sa.Integer(), nullable=False, comment='Auditor kaç kez reddetti (sahne anı için)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)', name=op.f('ck_messages_confidence_score_range')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('price_alerts',
    sa.Column('favorite_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.Enum('BELOW_AMOUNT', 'PERCENT_DROP', 'BACK_IN_STOCK', name='alert_type'), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='BELOW_AMOUNT için hedef fiyat'),
    sa.Column('percent_threshold', sa.Integer(), nullable=True, comment='PERCENT_DROP için yüzde'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorites.id'], name=op.f('fk_price_alerts_favorite_id_favorites'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_price_alerts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_alerts'))
    )
    op.create_index(op.f('ix_price_alerts_favorite_id'), 'price_alerts', ['favorite_id'], unique=False)
    op.create_table('price_histories',
    sa.Column('favorite_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_in_stock', sa.Boolean(), nullable=False),
    sa.Column('is_on_sale', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False, comment='Hangi platformdan çekildi (trendyol, hepsiburada, vs.)'),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorites.id'], name=op.f('fk_price_histories_favorite_id_favorites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_histories'))
    )
    op.create_index(op.f('ix_price_histories_captured_at'), 'price_histories', ['captured_at'], unique=False)
    op.create_index(op.f('ix_price_histories_favorite_id'), 'price_histories', ['favorite_id'], unique=False)
    op.create_index('ix_price_history_favorite_captured', 'price_histories', ['favorite_id', 'captured_at'], unique=False)
    op.create_table('recommendations',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('primary_product', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Ana tavsiye edilen ürün (name, price, platform, url, vs.)'),
    sa.Column('alternatives', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Alternatif ürünler'),
    sa.Column('reasoning', sa.Text(), nullable=False, comment='Neden bu ürün önerildi (markdown)'),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False, comment="AI'ın bu tavsiyeye güveni (0.00-1.00)"),
    sa.Column('market_consensus', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Forum, review, YouTube'dan toplanan piyasa görüşü"),
    sa.Column('financial_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Taksit, bütçe, hedef etkisi analizi'),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Kaynak linkler'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_recommendations_confidence_range')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_recommendations_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_index(op.f('ix_recommendations_conversation_id'), 'recommendations', ['conversation_id'], unique=False)
    op.create_table('message_feedbacks',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Enum('LIKE', 'DISLIKE', name='feedback_rating'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_feedbacks_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_message_feedbacks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_feedbacks')),
    sa.UniqueConstraint('message_id', name=op.f('uq_message_feedbacks_message_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_feedbacks')
    op.drop_index(op.f('ix_recommendations_conversation_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('ix_price_history_favorite_captured', table_name='price_histories')
    op.drop_index(op.f('ix_price_histories_favorite_id'), table_name='price_histories')
    op.drop_index(op.f('ix_price_histories_captured_at'), table_name='price_histories')
    op.drop_table('price_histories')
    op.drop_index(op.f('ix_price_alerts_favorite_id'), table_name='price_alerts')
    op.drop_table('price_alerts')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index('ix_favorites_user_folder', table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_index('ix_expenses_user_date', table_name='expenses')
    op.drop_index('ix_expenses_user_category', table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index('ix_conversations_user_status', table_name='conversations')
    op.drop_index('ix_conversations_user_last_message', table_name='conversations')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_share_token'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_last_message_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_folder_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_deleted_at'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('two_factor_secrets')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index('ix_sessions_user_expires', table_name='sessions')
    op.drop_index(op.f('ix_sessions_refresh_token_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_recurring_payments_user_id'), table_name='recurring_payments')
    op.drop_index(op.f('ix_recurring_payments_deleted_at'), table_name='recurring_payments')
    op.drop_table('recurring_payments')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_index('ix_push_subscriptions_user_active', table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_table('profiles')
    op.drop_table('preferences')
    op.drop_index('uq_oauth_provider_account', table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_user_id'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('notification_settings')
    op.drop_index(op.f('ix_folders_user_id'), table_name='folders')
    op.drop_table('folders')
    op.drop_table('financial_profiles')
    op.drop_index(op.f('ix_financial_goals_user_id'), table_name='financial_goals')
    op.drop_table('financial_goals')
    op.drop_index(op.f('ix_favorite_folders_user_id'), table_name='favorite_folders')
    op.drop_table('favorite_folders')
    op.drop_index(op.f('ix_credit_cards_user_id'), table_name='credit_cards')
    op.drop_index('ix_credit_cards_user_active', table_name='credit_cards')
    op.drop_index(op.f('ix_credit_cards_deleted_at'), table_name='credit_cards')
    op.drop_table('credit_cards')
    op.drop_index(op.f('ix_coupons_user_id'), table_name='coupons')
    op.drop_index('ix_coupons_user_expires', table_name='coupons')
    op.drop_index(op.f('ix_coupons_expires_at'), table_name='coupons')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_comparisons_user_id'), table_name='comparisons')
    op.drop_table('comparisons')
    op.drop_index('uq_budgets_user_category', table_name='budgets')
    op.drop_index(op.f('ix_budgets_user_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index('ix_audit_logs_user_occurred', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_occurred', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_email_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###